In [ ]:
import pandas as pd

series_dictionary = pd.Series({'b': 1, 'a': 0, 'c': 2})
series_dictionary.head()

series_array = pd.Series([3, 6, 9], index=['b', 'a', 'c'])
series_array.head()

series_single_value = pd.Series(1, index=['b', 'a', 'c'])
series_single_value.head()

b    1
a    1
c    1
dtype: int64

In [ ]:
print(len(series_dictionary))
print(len(series_array))
print(len(series_single_value))

3
3
3

In [ ]:
print(series_dictionary[0])
series_dictionary[[0]]

1

/tmp/ipython-input-38849551.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series_dictionary[0])
/tmp/ipython-input-38849551.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_dictionary[[0]]

b    1
dtype: int64

In [ ]:
series_array[[0, 2]]

/tmp/ipython-input-3980930488.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_array[[0, 2]]

b    3
c    9
dtype: int64

In [ ]:
series_array[[2, 0]]

/tmp/ipython-input-2294557873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_array[[2, 0]]

c    9
b    3
dtype: int64

In [ ]:
series_array[[2, 0]]

/tmp/ipython-input-2294557873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_array[[2, 0]]

c    9
b    3
dtype: int64

In [ ]:
print(series_array['c'])

9

In [ ]:
series_array[['c']]

c    9
dtype: int64

In [ ]:
series_array[['a', 'c']]

a    6
c    9
dtype: int64

In [ ]:
series_array[0:3]

b    3
a    6
c    9
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'a' : [2, 4, 8], 'b' : [3, 6, 9], 'c' : [5, 10, 15], 'd' : [7, 14, 21]})
df2 = pd.DataFrame(data=[[2, 3, 5, 7], [4, 6, 10, 14], [8, 9, 15, 21]], columns=['a', 'b', 'c', 'd'], index=['r1', 'r2', 'r3'])
df3 = pd.DataFrame(data=[[2, 3, 5, 7], [4, 6, np.nan, np.nan], [8, 9, 15, 21]], columns=['a', 'b', 'c', 'd'], index=['r1', 'r2', 'r3'])

In [ ]:
df1.head()

   a  b   c   d
0  2  3   5   7
1  4  6  10  14
2  8  9  15  21

In [ ]:
print(len(df1))
print(len(df1.columns))

3
4

In [ ]:
df1['a']

0    2
1    4
2    8
Name: a, dtype: int64

In [ ]:
df1[['a', 'd']]

   a   d
0  2   7
1  4  14
2  8  21

In [ ]:
df1.iloc[2]

a     8
b     9
c    15
d    21
Name: 2, dtype: int64

In [ ]:
df1.iloc[[2, 0]]

   a  b   c   d
2  8  9  15  21
0  2  3   5   7

In [ ]:
df2.loc['r1']

a    2
b    3
c    5
d    7
Name: r1, dtype: int64

In [ ]:
df2.loc[['r3', 'r1']]

    a  b   c   d
r3  8  9  15  21
r1  2  3   5   7

In [ ]:
df2[:]

    a  b   c   d
r1  2  3   5   7
r2  4  6  10  14
r3  8  9  15  21

In [ ]:
df2.iat[1, 3]

np.int64(14)